name: Master deployment

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

env:
  CI: true
  gitVersion: ${{ github.ref }}
  SAM_CLI_TELEMETRY: 0
  NODE_VERSION: "12.13.0"
  PYTHON_VERSION: "3.8"
  AWS_REGION: eu-west-1
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  AWS_RETRY_MODE: adaptive

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: prod

    env:
      env: prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install AWS SAM CLI
        run: pip3 install aws-sam-cli

      - name: Webpack build
        run: make build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CF_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CF_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Package CloudFormation
        run: make package

      - name: Deploy CloudFormation
        run: make deploy

      - name: Swagger
        run: make swagger
